/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;
import java.awt.Color;
import javax.swing.*;
import java.awt.*;
/**
/**
 *
 * @author USUARIO
 */
public class Modificar_Reserva extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Modificar_Reserva.class.getName());

    /**
     * Creates new form Modificar_Reserva
     */
    public Modificar_Reserva() {
        setUndecorated(true);

        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextNombre8 = new javax.swing.JTextField();
        jTextNombre9 = new javax.swing.JTextField();
        jTextNombre11 = new javax.swing.JTextField();
        jTextNombre10 = new javax.swing.JTextField();
        jTextNombre12 = new javax.swing.JTextField();
        jTextNombre13 = new javax.swing.JTextField();
        jTextNombre1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        exitBtn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextNombre8.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre8.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre8.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre8.setBorder(null);
        jTextNombre8.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre8.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre8.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 350, 20));

        jTextNombre9.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre9.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre9.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre9.setBorder(null);
        jTextNombre9.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre9.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre9.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre9ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 350, 20));

        jTextNombre11.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre11.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre11.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre11.setBorder(null);
        jTextNombre11.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre11.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre11.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre11.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre11ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 350, 20));

        jTextNombre10.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre10.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre10.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre10.setBorder(null);
        jTextNombre10.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre10.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre10.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre10.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre10ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 350, 20));

        jTextNombre12.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre12.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre12.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre12.setBorder(null);
        jTextNombre12.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre12.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre12.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre12.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre12ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 350, 20));

        jTextNombre13.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre13.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre13.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre13.setBorder(null);
        jTextNombre13.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre13.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre13.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre13.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre13ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 520, 200, 30));

        jTextNombre1.setBackground(new java.awt.Color(15, 22, 36));
        jTextNombre1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jTextNombre1.setForeground(new java.awt.Color(255, 255, 255));
        jTextNombre1.setBorder(null);
        jTextNombre1.setCaretColor(new java.awt.Color(255, 59, 107));
        jTextNombre1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextNombre1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        jTextNombre1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jTextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 520, 200, 30));

        jComboBox1.setBackground(new java.awt.Color(255, 59, 107));
        jComboBox1.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(15, 23, 36));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cédula de Ciudadanía ", "Cédula de Extranjería", "Pasaporte" }));
        jComboBox1.setBorder(null);
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setOpaque(false);
        jComboBox1.setVerifyInputWhenFocusTarget(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 280, 220, 30));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 670, 70, 80));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 670, 80, 70));

        exitBtn.setBackground(new java.awt.Color(255, 255, 255));
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setDoubleBuffered(false);
        exitBtn.setEnabled(false);
        exitBtn.setFocusable(false);
        exitBtn.setOpaque(false);
        exitBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(exitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 80, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Hotel\\src\\main\\java\\Interfaz\\Sources\\Modificar Reserva.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Documents\\NetBeansProjects\\Hotel\\src\\main\\java\\Interfaz\\Sources\\Modificar Reserva.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        Menu menu = new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextNombre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre8ActionPerformed

    private void jTextNombre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre9ActionPerformed

    private void jTextNombre11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre11ActionPerformed

    private void jTextNombre10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre10ActionPerformed

    private void jTextNombre12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre12ActionPerformed

    private void jTextNombre13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre13ActionPerformed

    private void jTextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Modificar_Reserva().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel exitBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextNombre1;
    private javax.swing.JTextField jTextNombre10;
    private javax.swing.JTextField jTextNombre11;
    private javax.swing.JTextField jTextNombre12;
    private javax.swing.JTextField jTextNombre13;
    private javax.swing.JTextField jTextNombre8;
    private javax.swing.JTextField jTextNombre9;
    // End of variables declaration//GEN-END:variables
}
