/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz.Sources;

/**
 *
 * @author USUARIO
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Reserva_bton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Hbitaciones_bton = new javax.swing.JButton();
        Cliente_bton = new javax.swing.JButton();
        Producto_bton = new javax.swing.JButton();
        Reporte_bton = new javax.swing.JButton();
        Registrar_client = new javax.swing.JButton();
        Registrar_produ = new javax.swing.JButton();
        Registrar_empleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Reserva_bton.setBorderPainted(false);
        Reserva_bton.setContentAreaFilled(false);
        Reserva_bton.setFocusPainted(false);
        Reserva_bton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reserva_btonActionPerformed(evt);
            }
        });
        jPanel1.add(Reserva_bton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 70, 70));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaz/Sources/Frame 3_1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Hbitaciones_bton.setText("jButton1");
        jPanel1.add(Hbitaciones_bton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 70, 70));

        Cliente_bton.setText("jButton1");
        jPanel1.add(Cliente_bton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 233, 70, 60));

        Producto_bton.setText("jButton1");
        jPanel1.add(Producto_bton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 353, 70, 60));
        jPanel1.add(Reporte_bton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 353, 70, 60));

        Registrar_client.setText("jButton1");
        jPanel1.add(Registrar_client, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 70, 30));

        Registrar_produ.setText("jButton1");
        jPanel1.add(Registrar_produ, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 93, -1, 20));

        Registrar_empleado.setText("jButton1");
        jPanel1.add(Registrar_empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 80, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Reserva_btonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reserva_btonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Reserva_btonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cliente_bton;
    private javax.swing.JButton Hbitaciones_bton;
    private javax.swing.JButton Producto_bton;
    private javax.swing.JButton Registrar_client;
    private javax.swing.JButton Registrar_empleado;
    private javax.swing.JButton Registrar_produ;
    private javax.swing.JButton Reporte_bton;
    private javax.swing.JButton Reserva_bton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
